### ISSUE TITLE
kernel_spec deprecated in IPython 3.0.0

### ISSUE THREAD

**Issue by titipata** [tribbloid/spookystuff#39]
I try to run `ipython notebook` with `profile spooky` on IPython notebook which came with Anaconda. However, I got this problem mentioned that `kernel_cmd` is deprecated. Is there any quick fix for that?

```
/home/ubuntu/anaconda/lib/python2.7/site-packages/IPython/kernel/manager.py:95: UserWarning: Setting kernel_cmd is deprecated, use kernel_spec to start different kernels.
  warnings.warn("Setting kernel_cmd is deprecated, use kernel_spec to "
Spark assembly has been built with Hive, including Datanucleus jars on classpath
Exception in thread "main" joptsimple.MultipleArgumentsForOptionException: Found multiple arguments for option ['profile'], but you asked for only one
	at joptsimple.OptionSet.valueOf(OptionSet.java:176)
	at org.tribbloid.ispark.Options.get(Options.scala:21)
	at org.tribbloid.ispark.Options.<init>(Options.scala:26)
	at org.tribbloid.ispooky.SpookyMain$.main(SpookyMain.scala:11)
	at org.tribbloid.ispooky.SpookyMain.main(SpookyMain.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:329)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
IPython Console 3.0.0
```

**Comment by H4ml3t** [comment]
Same problem here with python 3.1.0!

**Comment by titipata** [comment]
I did a quick fix by installing `IPython 2.4.1` (for now), it's a bit different way to customize your notebook right now. Maybe Peng has a good solution for that.
