### ISSUE TITLE
Error running examples after following installation instructions

### ISSUE THREAD

**Issue by nkconnor** [tribbloid/spookystuff#40]
Followed the instructions verbatim, and when trying to fire off an example I receive a `DFSWriteException` for trying to access the `spooky-page` bucket.

Where can I specify these options? Is there an example conf file floating around?

Thx.

```
15/05/23 16:59:40 ERROR Executor: Exception in task 7.0 in stage 3.0 (TID 115)
org.tribbloid.spookystuff.DFSWriteException: s3n://spooky-page/Wget('http/www.macys.com/'/true)--769004249/303688cd-9c02-4bf4-8a7e-b8e95c9aba5e
Caused by: org.apache.hadoop.fs.s3.S3Exception: org.jets3t.service.S3ServiceException: S3 HEAD request failed for '/Wget%28%27http%2Fwww.macys.com%2F%27%2Ftrue%29--769004249%2F303688cd-9c02-4bf4-8a7e-b8e95c9aba5e' - ResponseCode=403, ResponseMessage=Forbidden
	at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.retrieveMetadata(Jets3tNativeFileSystemStore.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:82)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:59)
	at org.apache.hadoop.fs.s3native.$Proxy4.retrieveMetadata(Unknown Source)
	at org.apache.hadoop.fs.s3native.NativeS3FileSystem.getFileStatus(NativeS3FileSystem.java:326)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:768)
	at org.tribbloid.spookystuff.pages.Page$$anonfun$save$1.apply$mcV$sp(Page.scala:98)
	at org.tribbloid.spookystuff.pages.Page$$anonfun$save$1.apply(Page.scala:94)
	at org.tribbloid.spookystuff.pages.Page$$anonfun$save$1.apply(Page.scala:94)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by nkconnor** [comment]
after resolving the conf issue inside `example.sh`, things look good until
```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.SQLContext.jsonRDD(Lorg/apache/spark/rdd/RDD;)Lorg/apache/spark/sql/DataFrame;
	at org.tribbloid.spookystuff.sparkbinding.PageRowRDD.toDataFrame(PageRowRDD.scala:111)
```

**Comment by nkconnor** [comment]
This is resolved by upgrading Spark
